### PR TITLE
Fix to require Bitcoin Core wallets loaded and RPC calls enabled

### LINKED ISSUE #6: [bug]: Doesn't work out the box
### Prerequisites

- [X] I have searched for existing issues that already report this problem.

### Device

Laptop/Desktop

### Device OS

Other

### Device OS Version

Embassy OS 0.3.3

### Browser

Chrome

### Browser Version

108.0.5359.125

### Current Behavior

After installing JAM from the marketplace, the JAM API isn't starting up

image

This results in the following error in the browser when clicking on the blue "Launch UI" button:

image

### Expected Behavior

The JAM API should boot

### Steps to Reproduce

1. Install JAM
2. Wait

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by islandbitcoin**
Addresses #6

### CODE REVIEW

File: scripts/services/dependencies.ts [hunk 1]
```diff
@@ -146,12 +149,16 @@ export const dependencies: T.ExpectedExports.dependencies = {
       if (!config.rpc.enable) {
         return { error: 'Must have RPC enabled' };
       }
+      if (!config.wallet.enable) {
+        return { error: 'Must have Bitcoin core wallet loaded and wallet RPC calls enabled' };
+      }
```
Comment (chrisguida) [inline scripts/services/dependencies.ts:154]: Do we enable wallet rpcs in proxy autoconfig?

**Review by kn0wmad — COMMENTED** [review]
Works for me in testing

File: scripts/services/dependencies.ts (hunk 1 above)
Comment (islandbitcoin) [reply scripts/services/dependencies.ts:154]: > 

yes

File: scripts/services/dependencies.ts [hunk 2]
```diff
@@ -146,12 +149,16 @@ export const dependencies: T.ExpectedExports.dependencies = {
...
       return { result: null };
     },
     // deno-lint-ignore require-await
     async autoConfigure(_effects, configInput) {
       const config = matchBitcoindConfig.unsafeCast(configInput);
       config.rpc.enable = true;
```
Comment (islandbitcoin) [inline scripts/services/dependencies.ts:160]: we enable RPC in autoconfig here @chrisguida

Comment (chrisguida) [reply scripts/services/dependencies.ts:160]: I was referring to the wallet rpc calls, since that's what's referred to in your above error message

Comment (islandbitcoin) [reply scripts/services/dependencies.ts:160]: > I was referring to the wallet rpc calls, since that's what's referred to in your above error message

this one boolean `wallet.enable` does both based on the description 

https://github.com/Start9Labs/jam-wrapper/issues/6#issuecomment-1365513602

Comment (chrisguida) [reply scripts/services/dependencies.ts:160]: No, I'm referring to adding the wallet rpc calls *themselves* (getwalletinfo, loadwallet, etc) to proxy's entry for the jam user. Does this PR do that?

Comment (chrisguida) [reply scripts/services/dependencies.ts:160]: This appears to just be autoconfiguring bitcoind, does it autoconfig proxy?

Comment (islandbitcoin) [reply scripts/services/dependencies.ts:160]: we have removed proxy from JAM completely, this service only uses bitcoind

Comment (chrisguida) [reply scripts/services/dependencies.ts:160]: Gotcha, thanks.

**Review by chrisguida — APPROVED** [review]
Looks good
